name: Update recent activity

on:
  schedule:
    # Every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  update-activity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update README with recent GitHub activity
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: MichaelPGifford
          COMMIT_MSG: "chore: refresh recent activity"
          MAX_LINES: 10
